"use client";

export {
  ArrowLeftIcon as ArrowLeft,
  BotIcon as Bot,
  BookTextIcon as BookOpen,
  BookmarkCheckIcon as BookMarked,
  CheckIcon as Check,
  CircleCheckIcon as CheckCircle2,
  ClockIcon as Clock,
  CloudUploadIcon as UploadCloud,
  CompassIcon as Compass,
  DatabaseIcon as Database,
  FlameIcon as Flame,
  HardDriveUploadIcon as HardDrive,
  HistoryIcon as History,
  HomeIcon as Home,
  KeyIcon as KeyRound,
  LanguagesIcon as Languages,
  LinkIcon as ExternalLink,
  ListIcon as Library,
  ListIcon as ListVideo,
  LoaderPinwheelIcon as Loader2,
  MenuIcon as Menu,
  PlayIcon as Play,
  RefreshCwIcon as RefreshCw,
  ScanTextIcon as Captions,
  SearchIcon as Search,
  ShieldCheckIcon as ShieldCheck,
  SlidersHorizontalIcon as SlidersHorizontal,
  SparklesIcon as Sparkles,
  TrendingUpIcon as TrendingUp,
  UserIcon as UserCircle,
  XIcon as X,
  XIcon as Trash2,
  YoutubeIcon as Video,
} from "lucide-animated";
